### ISSUE TITLE
WebView的高度wrap_content的时候，页面高度不对，会造成一系列的bug

### ISSUE THREAD

**Issue by zysidea** [wangzhengyi/Android-NestedDetail#12]
如果H5的高度不能铺满一屏幕，这样的体验很不好。我们把WebView的高度是wrap_content，会偶尔发生WebView的高度不对的问题，要么是高度小于内容高度，要么是大于。如果WebView的高度小于H5的高度，计算WebView是否滑到底就会有错误，就会造成一系列的滑动问题。我们尝试过onPageFinish和通过JS传递获取H5的高度来reSize WebView的高度，但是效果都不理想。

**Comment by wangzhengyi** [comment]
好的，我先看一下哈

Yanshi Zhang <notifications@github.com> 于2019年8月17日周六 下午4:59写道：

**Comment by wangzhengyi** [comment]
增加了JS方法回调，如果本地获取不准，可以让前端同学告知Web内容高度。如果内容高度小于容器高度时，动态设置容器高度为内容高度。
关闭该Issues。
