### ISSUE TITLE
computeScroll中的事件传递问题

### ISSUE THREAD

**Issue by AndyGu** [wangzhengyi/Android-NestedDetail#7]
NestedScrollingDetailContainer
line280 //滚动到父控件底部，滚动事件交给RecyclerView
如果recyclerView不足一屏（假设只有半屏），则在上半屏的webview的滑动手势都失效了

**Comment by AndyGu** [comment]
RecyclerView是不是不能把RecyclerView设成wrap_content？

**Comment by dnzl123** [comment]
我也遇到这个问题了，设置成match_parent,若果RecyclerView内容不足一屏，就显得很突兀。如果设置成wrap_content，那就则在上半屏的webview的滑动手势都失效了。

**Comment by dnzl123** [comment]
> RecyclerView是不是不能把RecyclerView设成wrap_content？

我也遇到这个问题了，请问你解决了吗

**Comment by wangzhengyi** [comment]
是个问题，我考虑一下
